kevin-lee/scala-hedgehog-extra

- .github/workflows/build.yml
- .github/workflows/sbt-build-all.sh
- build.sbt
- project/plugins.sbt
Add: GitHub Actions setup to build the project
> Add: GitHub Actions setup to build the project

- README.md
Add: build status and test codecov badges
> Add: build status and test codecov badges

- .scalafmt.conf
- build.sbt
> Clean up `build.sbt`

- build.sbt
- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/Gens.scala
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/GensSpec.scala
- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/StringGens.scala
> Clean up and renaming

- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/NumGens.scala
- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/StringGens.scala
Provide `Gens` `trait`s for `NumGens` and `StringGens`
> Provide `Gens` `trait`s for `NumGens` and `StringGens`

- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/NetGens.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/NetGensSpec.scala
Close #33 - Add `NetGens` with `PortNumber` generator
> Close #33 - Add NetGens with PortNumber generator

- project/plugins.sbt
Add: `sbt-devoops-starter` `2.23.0`
> Add: sbt-devoops-starter 2.23.0

- .github/workflows/release.yml
- build.sbt
- project/SbtProjectInfo.scala
- project/plugins.sbt
Add: GitHub Actions for release
> Add: GitHub Actions for release

- README.md
- build.sbt
Add: Missing project config for release
> Add: Missing project config for release

- build.sbt
Bump hedgehog `0.8.0` => `0.9.0`
> Bump hedgehog 0.8.0 => 0.9.0

- build.sbt
> Fix release setting

- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/StringGens.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/StringGensSpec.scala
Close #43 - Add `StringGens.genNonEmptyString`
> Close #43 - Add StringGens.genNonEmptyString

- project/plugins.sbt
Add: sbt plugin - `sbt-devoops-sbt-extra`
> Add: sbt plugin - sbt-devoops-sbt-extra

- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/NumGens.scala
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/NumGensSpec.scala
Close #52 - Add `Gen` for min and max pair for `Int` and `Long`
> Close #52 - Add Gen for min and max pair for Int and Long

- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/TimeGens.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/TimeGensSpec.scala
Close #54 - [`hedgehog-extra-refined`] Add `TimeGens` for `eu.timepit.refined.types.time` types
> Close #54 - [hedgehog-extra-refined] Add TimeGens for eu.timepit.refined.types.time types

- .scalafix-scala2.conf
- .scalafix-scala3.conf
Add: Scalafix - `.scalafix-scala2.conf` and `.scalafix-scala3.conf`
> Add: Scalafix - .scalafix-scala2.conf and .scalafix-scala3.conf

- .github/workflows/checks.yml
- build.sbt
- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/Gens.scala
- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/common.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/StringGensSpec.scala
Add: `checks.yml` and enable `scalafmt` and `scalafix` checks
> Add: checks.yml and enable scalafmt and scalafix checks

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/NumGensSpec.scala
- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/TimeGens.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/NumGensSpec.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/StringGensSpec.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/TimeGensSpec.scala
> Close #67 - Support Scala 3

- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/StringGens.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/StringGensSpec.scala
Close #71 - [`hedgehog-extra-refined`] Add `StringGens.genNonEmptyStringMinMax`
> Close #71 - [`hedgehog-extra-refined`] Add `StringGens.genNonEmptyStringMinMax`

- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/Gens.scala
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/GensSpec.scala
Close #73 - [`hedgehog-extra-core`] Add `Gens.genUnsafeNonWhitespaceStringMinMax`
> Close #73 - [hedgehog-extra-core] Add Gens.genUnsafeNonWhitespaceStringMinMax

- modules/hedgehog-extra-refined/src/main/scala/hedgehog/extra/refined/StringGens.scala
- modules/hedgehog-extra-refined/src/test/scala/hedgehog/extra/refined/StringGensSpec.scala
Close #75 - [`hedgehog-extra-refined`] Add `StringGens.genNonWhitespaceStringMinMax`
> Close #75 - [`hedgehog-extra-refined`] Add `StringGens.genNonWhitespaceStringMinMax`

- changelogs/0.1.0.md
- changelogs/0.2.0.md
- changelogs/0.3.0.md
- changelogs/0.4.0.md
Update old changelogs as the milestone names were changed
> Update old changelogs as the milestone names were changed

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
Close #83 - Upgrade Scala 3 to 3.1.3
> Close #83 - Upgrade Scala 3 to 3.1.3

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all-with-scala-version.sh
- .github/workflows/sbt-build-all.sh
- build.sbt
- modules/hedgehog-extra-refined4s/src/main/scala/hedgehog/extra/refined4s/gens/NetworkGens.scala
- modules/hedgehog-extra-refined4s/src/main/scala/hedgehog/extra/refined4s/gens/NumGens.scala
- modules/hedgehog-extra-refined4s/src/main/scala/hedgehog/extra/refined4s/gens/StringGens.scala
- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/NetworkGensSpec.scala
- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/NumGensSpec.scala
- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/StringGensSpec.scala
Close #80 - Add `hedgehog-extra-refined4s` to provide `Gen`s for `refined4s`'s pre-defined types
> Close #80 - Add `hedgehog-extra-refined4s` to provide `Gen`s for `refined4s`'s pre-defined types

- README.md
Update: `README.md` - with the latest release info
> Update: `README.md` - with the latest release info

- README.md
Update: `README.md` - with `hedgehog-extra-refined4s` info
> Update: `README.md` - with `hedgehog-extra-refined4s` info

- build.sbt
Close #90 - Upgrade `refined4s` to `0.13.0`
> Close #90 - Upgrade `refined4s` to `0.13.0`

- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/TimeGens.scala
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/TimeGensSpec.scala
Close #95 - [`hedgehog-extra-core`] Add `TimeGens.genInstant` to generate `java.time.Instant` with range
> Close #95 - [`hedgehog-extra-core`] Add `TimeGens.genInstant` to generate `java.time.Instant` with range

- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/TimeGens.scala
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/TimeGensSpec.scala
Close #97 - [`hedgehog-extra-core`] Add `TimeGens.genInstantFrom` to generate `java.time.Instant` with duration range
> Close #97 - [`hedgehog-extra-core`] Add `TimeGens.genInstantFrom` to generate `java.time.Instant` with duration range

- README.md
Update: `README.md` with the latest version info
> Update: `README.md` with the latest version info

- changelogs/0.5.0.md
- changelogs/0.6.0.md
- changelogs/0.7.0.md
> Fix old changelogs

- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/TimeGens.scala
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/TimeGensSpec.scala
Close #102 - [`hedgehog-extra-core`] Add `TimeGens.genLocalDate` to generate `java.time.LocalDate` with duration range
> Close #102 - [hedgehog-extra-core] Add TimeGens.genLocalDate to generate java.time.LocalDate with duration range

- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/TimeGensSpec.scala
Fix: Incorrect test info in the test description
> Fix: Incorrect test info in the test description

- modules/hedgehog-extra-core/src/main/scala/hedgehog/extra/TimeGens.scala
- modules/hedgehog-extra-core/src/test/scala/hedgehog/extra/TimeGensSpec.scala
Close #105 - [`hedgehog-extra-core`] Add `TimeGens.genLocalDateFrom` to generate `java.time.LocalDate` with duration range
> Close #105 - [`hedgehog-extra-core`] Add `TimeGens.genLocalDateFrom` to generate `java.time.LocalDate` with duration range

- modules/hedgehog-extra-refined4s/src/main/scala/hedgehog/extra/refined4s/gens/StringGens.scala
- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/StringGensSpec.scala
Close #109 - [`hedgehog-extra-refined4s`] Add `StringGens.genUuid` to generate `Uuid`
> Close #109 - [hedgehog-extra-refined4s] Add StringGens.genUuid to generate Uuid

- modules/hedgehog-extra-refined4s/src/main/scala/hedgehog/extra/refined4s/gens/StringGens.scala
- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/StringGensSpec.scala
Close #110 - [`hedgehog-extra-refined4s`] Add `StringGens.genNonBlankString` to generate `NonBlankString`
> Close #110 - [`hedgehog-extra-refined4s`] Add `StringGens.genNonBlankString` to generate `NonBlankString`

- modules/hedgehog-extra-refined4s/src/main/scala/hedgehog/extra/refined4s/gens/StringGens.scala
- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/StringGensSpec.scala
Close #113 - [`hedgehog-extra-refined4s`] Add `StringGens.genNonBlankStringMinMax` to generate `NonBlankString` with min and max lengths
> Close #113 - [`hedgehog-extra-refined4s`] Add `StringGens.genNonBlankStringMinMax` to generate `NonBlankString` with min and max lengths

- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/NumGensSpec.scala
- modules/hedgehog-extra-refined4s/src/test/scala/hedgehog/extra/refined4s/gens/StringGensSpec.scala
Clean up: Use of unnecessary unsafe smart constructors
> Clean up: Use of unnecessary unsafe smart constructors

- changelogs/0.9.0.md
* [`hedgehog-extra-core`] Add `TimeGens.genLocalDate` to
generate `java.time.LocalDate` with duration range (#102)
```scala
import hedgehog.extra._
import java.time.LocalDate
import java.time.temporal.ChronoUnit
for {
base      <- Gen.constant(LocalDate.now()).log("base")
from      <- Gen.constant(base.minus(100, ChronoUnit.DAYS)).log("from")
to        <- Gen.constant(base.plus(100, ChronoUnit.DAYS)).log("to")
localDate <- TimeGens.genLocalDate(from, to).log("localDate")
} yield {
???
}
```
* [`hedgehog-extra-core`] Add `TimeGens.genLocalDateFrom` to
generate `java.time.LocalDate` with duration range (#105)
```scala
import hedgehog.extra._
import scala.concurrent.duration._
import java.time.LocalDate
for {
base      <- Gen.constant(LocalDate.now()).log("base")
from      <- …
```
> scala-hedgehog-extra v0.9.0

- README.md
Update `README.md` with the latest version info
> Update `README.md` with the latest version info

- .gitignore
Update .gitignore to include additional build tool files
> Update .gitignore to include additional build tool files

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/release.yml
Update workflows to use `sbt/setup-sbt` with built-in caching.
> Update workflows to use `sbt/setup-sbt` with built-in caching.

- build.sbt
- project/plugins.sbt
Update Scala and sbt plugins, and remove unused scalafix config
- Bumped versions for Scala, dependencies, and sbt plugins.
- Removed outdated scalafix configuration and semanticdb version assignment.
> Update Scala and sbt plugins, and remove unused scalafix config

- build.sbt
- modules/hedgehog-extra-refined/shared/src/test/scala/hedgehog/extra/refined/NumGensSpec.scala
- project/build.properties
- project/plugins.sbt
* Bump sbt to 1.10.11
* Update Scala to 2.13.15 and plugin versions
> Bump sbt to 1.10.11 and update Scala to 2.13.15 and plugin versions

- project/build.properties
> Bump `sbt` to `1.11.2`

- build.sbt
- modules/hedgehog-extra-refined4s/shared/src/test/scala/hedgehog/extra/refined4s/gens/StringGensSpec.scala
Close #151: Bump `refined4s` to `1.8.1`
> Close #151: Bump `refined4s` to `1.8.1`
